<a href=galeri/0010izlemepaneli.png><img src="galeri/0010izlemepaneli.png" width="250" height="150" alt="0010izlemepaneli.png=n " /></a>
<a href=galeri/0050izlemepaneliservisler.png><img src="galeri/0050izlemepaneliservisler.png" width="250" height="150" alt="0050izlemepaneliservisler.png=n " /></a>
<a href=galeri/0100genelgorunum.png><img src="galeri/0100genelgorunum.png" width="250" height="150" alt="0100genelgorunum.png=n " /></a>
<a href=galeri/0200agaygitgorunumu.png><img src="galeri/0200agaygitgorunumu.png" width="250" height="150" alt="0200agaygitgorunumu.png=n " /></a>
<br /><br />
<a href=galeri/0300sisitemlerinayrintiligorunumu.png><img src="galeri/0300sisitemlerinayrintiligorunumu.png" width="250" height="150" alt="0300sisitemlerinayrintiligorunumu.png=n " /></a>
<a href=galeri/0400sistemdenetimlerilinux.png><img src="galeri/0400sistemdenetimlerilinux.png" width="250" height="150" alt="0400sistemdenetimlerilinux.png=n " /></a>
<a href=galeri/0500sistemdenetimlerilinuxgra.png><img src="galeri/0500sistemdenetimlerilinuxgra.png" width="250" height="150" alt="0500sistemdenetimlerilinuxgra.png=n " /></a>
<a href=galeri/0550sistemdenetimlerilinuxgra.png><img src="galeri/0550sistemdenetimlerilinuxgra.png" width="250" height="150" alt="0550sistemdenetimlerilinuxgra.png=n " /></a>
<br /><br />
<a href=galeri/0600sistemdenetimleriwindows.png><img src="galeri/0600sistemdenetimleriwindows.png" width="250" height="150" alt="0600sistemdenetimleriwindows.png=n " /></a>
<a href=galeri/0650sistemdenetimleriwindows.png><img src="galeri/0650sistemdenetimleriwindows.png" width="250" height="150" alt="0650sistemdenetimleriwindows.png=n " /></a>
<a href=galeri/0700sistemdenetimleriwindowsgra.png><img src="galeri/0700sistemdenetimleriwindowsgra.png" width="250" height="150" alt="0700sistemdenetimleriwindowsgra.png=n " /></a>
<a href=galeri/0750sistemdenetimleriwindowsgra.png><img src="galeri/0750sistemdenetimleriwindowsgra.png" width="250" height="150" alt="0750sistemdenetimleriwindowsgra.png=n " /></a>
<br /><br />
<a href=galeri/0800tarihcelinux.png><img src="galeri/0800tarihcelinux.png" width="250" height="150" alt="0800tarihcelinux.png=n " /></a>
<a href=galeri/0850tarihcelinux.png><img src="galeri/0850tarihcelinux.png" width="250" height="150" alt="0850tarihcelinux.png=n " /></a>
<a href=galeri/1000sistemler.png><img src="galeri/1000sistemler.png" width="250" height="150" alt="1000sistemler.png=n " /></a>
<a href=galeri/1050uyariturleri.png><img src="galeri/1050uyariturleri.png" width="250" height="150" alt="1050uyariturleri.png=n " /></a>
<br /><br />
<a href=galeri/1100bilgiler.png><img src="galeri/1100bilgiler.png" width="250" height="150" alt="1100bilgiler.png=n " /></a>
<a href=galeri/1150denetimler.png><img src="galeri/1150denetimler.png" width="250" height="150" alt="1150denetimler.png=n " /></a>
<a href=galeri/1200sistemtipleri.png><img src="galeri/1200sistemtipleri.png" width="250" height="150" alt="1200sistemtipleri.png=n " /></a>
<a href=galeri/1250sistemdenetimleriwindows.png><img src="galeri/1250sistemdenetimleriwindows.png" width="250" height="150" alt="1250sistemdenetimleriwindows.png=n " /></a>
<br /><br />
<a href=galeri/1300sistemdenetimlerilinux.png><img src="galeri/1300sistemdenetimlerilinux.png" width="250" height="150" alt="1300sistemdenetimlerilinux.png=n " /></a>
<a href=galeri/1350sistemdenetimleridurumlari.png><img src="galeri/1350sistemdenetimleridurumlari.png" width="250" height="150" alt="1350sistemdenetimleridurumlari.png=n " /></a>
<a href=galeri/1400sistemuyarileri.png><img src="galeri/1400sistemuyarileri.png" width="250" height="150" alt="1400sistemuyarileri.png=n " /></a>
<a href=galeri/1500otomatiksistemalgilama.png><img src="galeri/1500otomatiksistemalgilama.png" width="250" height="150" alt="1500otomatiksistemalgilama.png=n " /></a>
<br /><br />
<a href=galeri/1550arayuz.png><img src="galeri/1550arayuz.png" width="250" height="150" alt="1550arayuz.png=n " /></a>
<a href=galeri/1600kullanicilar.png><img src="galeri/1600kullanicilar.png" width="250" height="150" alt="1600kullanicilar.png=n " /></a>
