%define name sisiya-edbc-libs

%define version 0.1.3
%define release 21

%define install_dir /opt/%{name}

Summary: The SisIYA server / remote check programs that are run from a central server. This is normally the server where SisIYA daemon runs.
Name:%{name} 
BuildArch: noarch
BuildRoot: %{_builddir}/%{name}-root
Version: %{version}
Release: %{release}
#Obsoletes: $version-$release
Source0: %{name}-%{version}-%{release}.tar.gz
#Source1: http://download.sourceforge.net/sisiya/%{name}-%{version}-%{release}.tar.gz
License: GPL
Vendor: Erdal Mutlu
Group: System Environment/Daemons
Packager: Erdal Mutlu <emutlu@users.sourceforge.net>
Url: http://sisiya.sourceforge.net
Requires: bash, sisiya-client-checks >= 0.5, bind-utils, curl, expect, ftp, gawk, iputils, net-snmp, net-snmp-utils, samba-client, wget
%description 
This package contains the SisIYA EDBC libraries.

%prep 
%setup -n %{name}-%{version}-%{release}

%build
### configure & compile
make 

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}

### install edbc
cd edbc && make "install_root=%{buildroot}" install && cd ..

### remove Helvetica.ttf font file which is auto generated by doxygen
rm -f %{buildroot}/opt/sisiya_edbc_docs/latex/Helvetica.ttf

%pre

%clean 
rm -rf %{buildroot}

%files edbc-libs
%defattr(-,root,root)
#%attr(0644,root,root) %doc README NEWS ChangeLog AUTHORS INSTALL TODO
%attr(0755,root,root) 					/opt/sisiya_edbc/lib/*.so
%attr(-,root,root) 					/opt/sisiya_edbc/lib/*.so.%{sisiya_EDBCVersion}
