'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SisIYA.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property back32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ConflictIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ConflictIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Down_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Down_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Down_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Down_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Error_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Error_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Error_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HataIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("HataIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ico_info() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_info", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property import64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("import64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Info_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Info_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Info_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Info_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ok_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Ok_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Ok_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ok_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ProgressError() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ProgressError", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ProgressWarn() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ProgressWarn", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property S_Down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S_Down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property S_Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property S_Info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S_Info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property S_Ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S_Ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property S_Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("S_Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sisicon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sisicon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sisiya_client_app_18() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("sisiya_client_app_18", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property sisiya_client_gui() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("sisiya_client_gui", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property sisiya_client_gui_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sisiya_client_gui_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sisiya_client_gui_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sisiya_client_gui_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sisiya_k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sisiya_k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UayriIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("UayriIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Warn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Warning_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Warning_26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Warning_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
