insert into users values(-1,'admin','\$1\$xotkYPkm\$Xvcb5nKLwjMhWUrIhiZ1I.','System','Administrator','admins@example.com','t');

insert into alerttypes values(2,'E-Mail');
insert into alerttypes values(3,'SMS');
insert into alerttypes values(4,'Jabber');

insert into infos values(1,0,'Description');
insert into infos values(2,0,'Vendor');
insert into infos values(3,0,'Model');
insert into infos values(4,0,'CPU');
insert into infos values(5,0,'HD');
insert into infos values(6,0,'RAM');
insert into infos values(7,0,'Size');
insert into infos values(8,0,'System Tag');
insert into infos values(9,0,'BIOS Version');
insert into infos values(10,0,'Backplane Version');
insert into infos values(11,0,'RAID Controller');
insert into infos values(12,0,'RAID Level');
insert into infos values(13,0,'Serial Number');
insert into infos values(14,0,'Support Type');
insert into infos values(15,0,'Inventory Number');
insert into infos values(16,0,'Operating System');
insert into infos values(17,0,'Support Number');
insert into infos values(18,0,'PROM');
insert into infos values(19,0,'Cluster');
insert into infos values(20,0,'HostID');
insert into infos values(21,0,'SCSI Adapter');

insert into languages values(0,'en','English','utf-8');
insert into languages values(1,'tr','Turkish','utf-8');

insert into locations values(1,2,'Server Room');
insert into locations values(2,1,'Server Center');
insert into locations values(3,3,'Home');

insert into properties values(1,'Jabber ID');

insert into services values(0,'System');
insert into services values(1,'Filesystem');
insert into services values(2,'CPU');
insert into services values(3,'SWAP');
insert into services values(4,'Load');
insert into services values(5,'SMTP');
insert into services values(6,'SMB');
insert into services values(7,'NMB');
insert into services values(8,'PostgreSQL');
insert into services values(9,'MySQL');
insert into services values(10,'Oracle');
insert into services values(11,'IMAP');
insert into services values(12,'POP3');
insert into services values(13,'Lotus');
insert into services values(14,'Printer');
insert into services values(15,'FTP');
insert into services values(16,'Squid');
insert into services values(17,'DNS');
insert into services values(18,'NFS');
insert into services values(19,'DHCP');
insert into services values(20,'HTTP');
insert into services values(21,'HTTPS');
insert into services values(22,'Ping');
insert into services values(23,'Telnet');
insert into services values(24,'Postfix');
insert into services values(25,'xinetd');
insert into services values(26,'sshd');
insert into services values(27,'xfs');
insert into services values(28,'kdm');
insert into services values(29,'portmap');
insert into services values(30,'atalkd');
insert into services values(31,'afpd');
insert into services values(32,'papd');
insert into services values(33,'RAM');
insert into services values(34,'nmbd');
insert into services values(35,'Solstice');
insert into services values(36,'rpcstatd');
insert into services values(37,'rpcrquotad');
insert into services values(38,'rpcmountd');
insert into services values(39,'nfsd');
insert into services values(40,'lockd');
insert into services values(41,'rpciod');
insert into services values(42,'slapd');
insert into services values(43,'SunCluster');
insert into services values(44,'inetd');
insert into services values(45,'users');
insert into services values(46,'Veritas');
insert into services values(47,'Netstat');
insert into services values(48,'PROGS');
insert into services values(49,'Porgs');
insert into services values(50,'SSH');
insert into services values(51,'OracleTBS');
insert into services values(52,'DominoWebAccount');
insert into services values(53,'NetBackup_Jobs');
insert into services values(54,'NetBackup_Debug');
insert into services values(55,'NetBackup_Drives');
insert into services values(56,'NetBackup_Clients');
insert into services values(57,'NetBackup_Library');
insert into services values(58,'Oracle_Hitratios');
insert into services values(59,'NetBackup_Robots');
insert into services values(60,'UPS_Battery');
insert into services values(61,'Temperature');
insert into services values(62,'UPS_Status');
insert into services values(63,'UPS_Output');
insert into services values(64,'UPS_TimeOnBattery');
insert into services values(65,'PDU_Output');
insert into services values(66,'Battery');
insert into services values(67,'NetBackup_Scratch');
insert into services values(68,'NetBackup_Notify');
insert into services values(69,'Printer_PageCounts');
insert into services values(70,'BatchJob_Notify');
insert into services values(71,'NetBackup_Frozen');
insert into services values(72,'Daemon_Childs');
insert into services values(73,'Dmesg');
insert into services values(74,'Test');
insert into services values(75,'Listening');
insert into services values(76,'NTP');
insert into services values(77,'IP');
insert into services values(78,'MySQL');
insert into services values(79,'Established');
insert into services values(80,'HDD');
insert into services values(81,'RAID');
insert into services values(82,'Fan_Speed');
insert into services values(83,'Baan');
insert into services values(84,'Baan');
insert into services values(85,'LPstat');
insert into services values(90,'SMART');
insert into services values(91,'MSSQL');
insert into services values(92,'Line');
insert into services values(93,'Port');
insert into services values(94,'SNMP');
insert into services values(95,'Software');
insert into services values(96,'Mail');
insert into services values(97,'PowerSupply');
insert into services values(98,'VMware');
insert into services values(99,'EventLog');
insert into services values(100,'Uptodate');
insert into services values(101,'Antivirus');
insert into services values(102,'Services');
insert into services values(103,'Brightstore_Jobs');
insert into services values(104,'BrightStore_Devices');
insert into services values(105,'BrightStore_Scratch');
insert into services values(120,'MSExchange');
insert into services values(121,'MSExchange');
insert into services values(122,'MSExchange');
insert into services values(5000,'Online');
insert into services values(5001,'Baan');
insert into services values(5002,'Baan');

insert into status values(0,'Info');
insert into status values(1,'Ok');
insert into status values(2,'Warning');
insert into status values(3,'Error');

insert into systemtypes values(1,'Linux');
insert into systemtypes values(2,'Solaris');
insert into systemtypes values(3,'Windows');
insert into systemtypes values(4,'MacOS_X');
insert into systemtypes values(5,'HPProCurve');
insert into systemtypes values(6,'APCPowerSwitch');
insert into systemtypes values(7,'Airport');
insert into systemtypes values(8,'HPPrinter');
insert into systemtypes values(9,'EpsonPrinter');
insert into systemtypes values(10,'OCE');
insert into systemtypes values(11,'HPDigitalSender');
insert into systemtypes values(12,'APCUPS');
insert into systemtypes values(13,'Kyocera');
insert into systemtypes values(14,'DellSwitch');
insert into systemtypes values(15,'Netscreen');
insert into systemtypes values(16,'Netgear');
insert into systemtypes values(17,'Apache');
insert into systemtypes values(18,'Siemens');
insert into systemtypes values(19,'CISCO');
insert into systemtypes values(20,'HP-UX');
insert into systemtypes values(21,'AlliedTelesyn');
insert into systemtypes values(22,'Zoom');
insert into systemtypes values(23,'AirTies');
insert into systemtypes values(24,'Digitus');
insert into systemtypes values(25,'Alcatel');
insert into systemtypes values(26,'ZyXEL');
insert into systemtypes values(27,'Ricoh');
insert into systemtypes values(28,'Orme');
insert into systemtypes values(29,'DLink');
insert into systemtypes values(30,'USRobotics');
insert into systemtypes values(31,'NRG');
insert into systemtypes values(32,'Repotec');
insert into systemtypes values(33,'AIX');
insert into systemtypes values(34,'NetBSD');
insert into systemtypes values(35,'OpenBSD');
insert into systemtypes values(36,'FreeBSD');
insert into systemtypes values(37,'OpenSolaris');
insert into systemtypes values(38,'VMware');

insert into systems values(1,'t',1,1,'server1','server1.example.org','t');
insert into systems values(2,'t',2,1,'server2','server2.example.org','t');
insert into systems values(3,'t',3,1,'server3','server3.example.org','t');
insert into systems values(4,'t',4,1,'server4','server4.example.org','t');

