### directory definitions #################################################
install_root=$(DESTDIR)$(prefix)
web_dir=$(install_root)$(WEB_BASE_DIR)/sisiya-webui-php
###########################################################################

install:
	install -m 755 -d 				$(web_dir)/images/systems
	install -m 644 *.gif				$(web_dir)/images/systems/
