### directory definitions #################################################
install_root=$(DESTDIR)$(prefix)
web_dir=$(install_root)/var/lib/sisiya-webui-images
###########################################################################

install:
	install -m 755 -d 				$(web_dir)
	install -m 644 *.gif				$(web_dir)
