delete from interface;
delete from strkeys;
insert into strkeys values(1,'sisiya_admin.alerttypes.header','Header of the alerttypes page');
insert into interface values(0,1,'Alert Types');
insert into interface values(1,1,'Uyarı Türleri');
insert into strkeys values(2,'sisiya_admin.alerttypes.label.id','ID label on the alerttypes page');
insert into interface values(0,2,'ID');
insert into interface values(1,2,'No');
insert into strkeys values(3,'sisiya_admin.alerttypes.label.keystr','Alert Type label on the alerttypes page');
insert into interface values(0,3,'Alert Type');
insert into interface values(1,3,'Uyarı Türü');
insert into strkeys values(4,'sisiya_admin.alerttypes.title','Title of the alerttypes page');
insert into interface values(0,4,'Alert Types');
insert into interface values(1,4,'Uyarı Türleri');
insert into strkeys values(5,'sisiya_admin.button.add.description','Add button description');
insert into interface values(0,5,'Add record');
insert into interface values(1,5,'Kayıt ekle');
insert into strkeys values(6,'sisiya_admin.button.add','Add button');
insert into interface values(0,6,'Add record');
insert into interface values(1,6,'Kayıt ekle');
insert into strkeys values(7,'sisiya_admin.button.change','Change button');
insert into interface values(0,7,'Change');
insert into interface values(1,7,'Değiştir');
insert into strkeys values(8,'sisiya_admin.button.clear.description','Clear button description');
insert into interface values(0,8,'Clear fields');
insert into interface values(1,8,'Alanları temizle');
insert into strkeys values(9,'sisiya_admin.button.clear','Clear button');
insert into interface values(0,9,'Clear fields');
insert into interface values(1,9,'Alanları temizle');
insert into strkeys values(10,'sisiya_admin.button.delete.description','Delete button description');
insert into interface values(0,10,'Delete record');
insert into interface values(1,10,'Kaydı sil');
insert into strkeys values(11,'sisiya_admin.button.delete','Delete button');
insert into interface values(0,11,'Delete record');
insert into interface values(1,11,'Kaydı sil');
insert into strkeys values(12,'sisiya_admin.button.export','Export button');
insert into interface values(0,12,'Export');
insert into interface values(1,12,'Dışa çık');
insert into strkeys values(13,'sisiya_admin.button.find','Find button');
insert into interface values(0,13,'Find');
insert into interface values(1,13,'Bul');
insert into strkeys values(14,'sisiya_admin.button.forgot_password','Forgot password button');
insert into interface values(0,14,'Forgot password');
insert into interface values(1,14,'Şifremi unuttum');
insert into strkeys values(15,'sisiya_admin.button.insert','Insert button');
insert into interface values(0,15,'Insert');
insert into interface values(1,15,'Gir');
insert into strkeys values(16,'sisiya_admin.button.login','Login button');
insert into interface values(0,16,'Login');
insert into interface values(1,16,'Giriş');
insert into strkeys values(17,'sisiya_admin.button.logout','Logout button');
insert into interface values(0,17,'Logout');
insert into interface values(1,17,'Çıkış');
insert into strkeys values(18,'sisiya_admin.button.search.description','Search button description');
insert into interface values(0,18,'Search records');
insert into interface values(1,18,'Kayıtlarda ara');
insert into strkeys values(19,'sisiya_admin.button.search','Search button');
insert into interface values(0,19,'Search records');
insert into interface values(1,19,'Kayıtlarda ara');
insert into strkeys values(20,'sisiya_admin.button.send.description','Send button description');
insert into interface values(0,20,'Send message');
insert into interface values(1,20,'İletiyi gönder');
insert into strkeys values(21,'sisiya_admin.button.send','Send button');
insert into interface values(0,21,'Send message');
insert into interface values(1,21,'İletiyi gönder');
insert into strkeys values(22,'sisiya_admin.button.update.description','Update button description');
insert into interface values(0,22,'Update record');
insert into interface values(1,22,'Kaydı güncelle');
insert into strkeys values(23,'sisiya_admin.button.update','Update button');
insert into interface values(0,23,'Update record');
insert into interface values(1,23,'Kaydı güncelle');
insert into strkeys values(24,'sisiya_admin.change_password.header','Header of the change_password page');
insert into interface values(0,24,'Change Password');
insert into interface values(1,24,'Şifre Değiştirme');
insert into strkeys values(25,'sisiya_admin.change_password.label.new_password','New password label on the change_password page');
insert into interface values(0,25,'New password');
insert into interface values(1,25,'Yeni şifre');
insert into strkeys values(26,'sisiya_admin.change_password.label.old_password','Old password label on the change_password page');
insert into interface values(0,26,'Old password');
insert into interface values(1,26,'Eski şifre');
insert into strkeys values(27,'sisiya_admin.change_password.label.renew_password','Re new password label on the change_password page');
insert into interface values(0,27,'Re new password');
insert into interface values(1,27,'Yeni şifre tekrar');
insert into strkeys values(28,'sisiya_admin.change_password.title','Title of the change_password page');
insert into interface values(0,28,'Change Password');
insert into interface values(1,28,'Şifre Değiştirme');
insert into strkeys values(29,'sisiya_admin.group_systems.header','Header of the group_systems page');
insert into interface values(0,29,'Group Systems');
insert into interface values(1,29,'Sistemleri Grupla');
insert into strkeys values(30,'sisiya_admin.group_systems.label.group_id','Group ID label on the group_systems page');
insert into interface values(0,30,'Group');
insert into interface values(1,30,'Grup');
insert into strkeys values(31,'sisiya_admin.group_systems.title','Title of the group_systems page');
insert into interface values(0,31,'Group Systems');
insert into interface values(1,31,'Sistemleri Grupla');
insert into strkeys values(32,'sisiya_admin.infos.header','Header of the infos page');
insert into interface values(0,32,'Infos');
insert into interface values(1,32,'Bilgiler');
insert into strkeys values(33,'sisiya_admin.infos.label.id','ID label on the infos page');
insert into interface values(0,33,'ID');
insert into interface values(1,33,'No');
insert into strkeys values(34,'sisiya_admin.infos.label.keystr','Status label on the infos page');
insert into interface values(0,34,'Infos');
insert into interface values(1,34,'Bilgi');
insert into strkeys values(35,'sisiya_admin.infos.label.sortid','Sort ID label on the infos page');
insert into interface values(0,35,'Sort ID');
insert into interface values(1,35,'Sıra No');
insert into strkeys values(36,'sisiya_admin.infos.title','Title of the infos page');
insert into interface values(0,36,'Infos');
insert into interface values(1,36,'Bilgiler');
insert into strkeys values(37,'sisiya_admin.interface.header','Header of the interface form');
insert into interface values(0,37,'Web interface');
insert into interface values(1,37,'Web arayüzü');
insert into strkeys values(38,'sisiya_admin.interface.label.keystr','Key string label in the interface form');
insert into interface values(0,38,'String key');
insert into interface values(1,38,'Anahtar sözcük');
insert into strkeys values(39,'sisiya_admin.interface.label.language','Language label in the interface form');
insert into interface values(0,39,'Language');
insert into interface values(1,39,'Dil');
insert into strkeys values(40,'sisiya_admin.interface.label.text','Text label in the interface form');
insert into interface values(0,40,'Text');
insert into interface values(1,40,'Metin');
insert into strkeys values(41,'sisiya_admin.interface.title','Title of the interface form');
insert into interface values(0,41,'Web interface');
insert into interface values(1,41,'Web arayüzü');
insert into strkeys values(42,'sisiya_admin.label.description_alert_frequency','Alert frequency description label');
insert into interface values(0,42,'0 : never, n : every n minutes');
insert into interface values(1,42,' 0 : hiçbir zaman, n : her n dakikada bir');
insert into strkeys values(43,'sisiya_admin.label.alert_frequency','Alert frequency label');
insert into interface values(0,43,'Alert frequency');
insert into interface values(1,43,'Uyarı sıklığı');
insert into strkeys values(44,'sisiya_admin.label.change_time','Change time label');
insert into interface values(0,44,'Change Time');
insert into interface values(1,44,'Durum Değişme Saati');
insert into strkeys values(45,'sisiya_admin.label.expires','Expires label');
insert into interface values(0,45,'Expires');
insert into interface values(1,45,'Son kullanımı');
insert into strkeys values(46,'sisiya_admin.label.is_active','Is active label');
insert into interface values(0,46,'Is active?');
insert into interface values(1,46,'Etkin mi?');
insert into strkeys values(47,'sisiya_admin.label.isactive','Is active label');
insert into interface values(0,47,'Is active?');
insert into interface values(1,47,'Kullanımda mı?');
insert into strkeys values(48,'sisiya_admin.label.message','Message label');
insert into interface values(0,48,'Message');
insert into interface values(1,48,'Ayrıntısı');
insert into strkeys values(49,'sisiya_admin.label.no','No label');
insert into interface values(0,49,'No');
insert into interface values(1,49,'Hayır');
insert into strkeys values(50,'sisiya_admin.label.orderby','Order by label in forms');
insert into interface values(0,50,'Order by');
insert into interface values(1,50,'Sıralama koşulu');
insert into strkeys values(51,'sisiya_admin.label.service','Service label');
insert into interface values(0,51,'Service');
insert into interface values(1,51,'Denetimi');
insert into strkeys values(52,'sisiya_admin.label.sortid','Sort ID label');
insert into interface values(0,52,'Sort ID');
insert into interface values(1,52,'Sıra No');
insert into strkeys values(53,'sisiya_admin.label.status','Status label');
insert into interface values(0,53,'Status');
insert into interface values(1,53,'Durumu');
insert into strkeys values(54,'sisiya_admin.label.system','System label');
insert into interface values(0,54,'System');
insert into interface values(1,54,'Sistem');
insert into strkeys values(55,'sisiya_admin.label.update_time','Update time label');
insert into interface values(0,55,'Update Time');
insert into interface values(1,55,'Güncelleme Saati');
insert into strkeys values(56,'sisiya_admin.label.yes','Yes label');
insert into interface values(0,56,'Yes');
insert into interface values(1,56,'Evet');
insert into strkeys values(57,'sisiya_admin.languages.header','Header of the languages form');
insert into interface values(0,57,'Languages');
insert into interface values(1,57,'Diller');
insert into strkeys values(58,'sisiya_admin.languages.label.charset','Charset label in the languages form');
insert into interface values(0,58,'Charset');
insert into interface values(1,58,'Karakter seti');
insert into strkeys values(59,'sisiya_admin.languages.label.code','Code label in the languages form');
insert into interface values(0,59,'Code');
insert into interface values(1,59,'Kod');
insert into strkeys values(60,'sisiya_admin.languages.label.id','ID label in the languages form');
insert into interface values(0,60,'ID');
insert into interface values(1,60,'No');
insert into strkeys values(61,'sisiya_admin.languages.label.language','Language label in the languages form');
insert into interface values(0,61,'Language');
insert into interface values(1,61,'Dil');
insert into strkeys values(62,'sisiya_admin.languages.title','Title of the languages form');
insert into interface values(0,62,'Languages');
insert into interface values(1,62,'Diller');
insert into strkeys values(63,'sisiya_admin.locations.header','Header of the locations page');
insert into interface values(0,63,'Locations');
insert into interface values(1,63,'Konumlar');
insert into strkeys values(64,'sisiya_admin.locations.label.id','ID label on the locations page');
insert into interface values(0,64,'ID');
insert into interface values(1,64,'No');
insert into strkeys values(65,'sisiya_admin.locations.label.keystr','Status label on the locations page');
insert into interface values(0,65,'Location');
insert into interface values(1,65,'Konum');
insert into strkeys values(66,'sisiya_admin.locations.label.sortid','Sort ID label on the locations page');
insert into interface values(0,66,'Sort ID');
insert into interface values(1,66,'Sıra No');
insert into strkeys values(67,'sisiya_admin.locations.title','Title of the locations page');
insert into interface values(0,67,'Locations');
insert into interface values(1,67,'Konumlar');
insert into strkeys values(68,'sisiya_admin.login.click_to_proceed','Click here to proceed');
insert into interface values(0,68,'Click here to proceed.');
insert into interface values(1,68,'Devam etmek için tıklayın.');
